version: '{branch}_1.0.{build}'
image:
  - Visual Studio 2017
configuration:
  - Release
clone_folder: c:\projects\source
skip_non_tags: true
platform:
  - x64

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake c:\projects\source -G "Visual Studio 15"

build_script:
  - cmd: cmake --build . --config %CONFIGURATION%

artifacts:
  path: build\%CONFIGURATION%\*.exe
  name: binary_executable
