language: cpp
dist: trusty

before_script:
  - mkdir build
  - cd build
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      mkdir -p external/cmake
      pushd external/cmake
      wget https://cmake.org/files/v3.16/cmake-3.16.0-Linux-x86_64.sh
      chmod +x cmake-*-Linux-x86_64.sh
      ./cmake-*-Linux-x86_64.sh --exclude-subdir --skip-license
      export PATH="${PWD}/bin:$PATH"
      popd
    else
      if ! brew ls --version cmake &>/dev/null; then brew update; brew install cmake; fi
    fi

matrix:
  include:
    - os: osx
      compiler: clang
      env:
        - TEST="Xcode 11"
      osx_image: xcode11
      script:
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - cmake --build .
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
          - eval "${MATRIX_EVAL}"
      script:
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - cmake --build .